In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
data = [None] * 6
data[0] = pd.read_csv('data-1.csv')
data[1] = pd.read_csv('data-2.csv')
data[2] = pd.read_csv('data-3.csv')
data[3] = pd.read_csv('data-4.csv')
data[4] = pd.read_csv('data-5.csv')
data[5] = pd.read_csv('data-6.csv')

In [3]:
def generate_summary(data, idx):
    #Mean
    dmean = data.mean(axis=0)
    #print("Mean")
    #print(dmean, end='\n\n')
    #print(dmean.x)
    #Standard Deviation
    dstd = data.std(axis=0)
    #print("Standard Deviation")
    #print(dstd, end='\n\n')

    dmin = data.min(axis=0)
    #print("Min")
    #print(dmin, end='\n\n')

    dmax = data.max(axis=0)
   # print("Max")
    #print(dmax, end='\n\n')

    ranged = dmax - dmin
    #print("Range")
    #print(ranged, end='\n\n')

    dcorr = data.x.corr(data.y, method='pearson')
   # print('Correlation Coefficient')
    #print(dcorr)
    
    df =  pd.DataFrame(
        {
            "Mean X": dmean.x,
            "Mean Y": dmean.y,
            "Stdev X": dstd.x,
            "Stdev Y": dstd.y,
            "Min X": dmin.x,
            "Min Y": dmin.y,
            "Max X": dmax.x,
            "Max Y": dmax.y,
            "Range X": ranged.x,
            "Range Y": ranged.y,
            "Correlation Coefficient": dcorr
        },
            index = ["Dataset" + str(idx)]
        )
    #print(df)
    return df

In [4]:
summary = pd.DataFrame()
i = 1
for d in data:
    summary = summary.append(generate_summary(d, i))
    i = i + 1
summary

,Mean X,Mean Y,Stdev X,Stdev Y,Min X,Min Y,Max X,Max Y,Range X,Range Y,Correlation Coefficient
Dataset1,8.717696,12.522874,12.155517,6.639964,-22.635878,-2.565088,35.237055,27.384153,57.872933,29.949240,0.950326
Dataset2,-0.710787,-0.748987,11.481584,6.257918,-33.271113,-18.621804,27.647000,14.147315,60.918113,32.769119,0.955153
Dataset3,0.968907,8.508535,2.235558,1.149301,-2.449064,6.641734,4.518885,10.551871,6.967949,3.910137,0.981937
Dataset4,49.905086,18.553837,28.508611,16.545896,0.000000,0.000000,87.376700,44.565040,87.376700,44.565040,-0.081193
Dataset5,49.909994,18.555525,28.500001,16.540796,4.337892,0.055498,91.052863,49.934197,86.714971,49.878700,-0.088236
Dataset6,7.216155,7.602215,11.921599,11.764382,-24.333821,-22.956357,35.402139,36.079874,59.735960,59.036231,0.935069

In [5]:
with open('summary.txt','w') as output:
    summary.to_string(output)

In [ ]:
#Data-1: Dataset with large positive correlation between x and y, ranging from -22.64 to 35.24 for x and -2.57 to 27.38 for y.
#Data-2: Dataset with large positive correlation between x and y, ranging from -33.27 to 27.65 for x and -18.62 to 14.15 for y.
#Data-3: Dataset with large positive correlation between x and y, ranging for -2.45 to 4.52 for x and -18.62 to 14.15 for y.
#Data-4: Dataset with no correlation with a mean x value of 49.91 and mean y value of 18.55 with x and y values centered more around the mean, like a standard distribution.
#Data-5: Dataset with no correlation with a mean x value of 49.91 and mean y value of 18.56, with x and y